version: '3.9'

services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - backend

  backend:
    build:
      context: ./estechbackend
    volumes:
      - ./estechbackend:/app
    env_file:
      - ./estechbackend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend

  frontend:
    build:
      context: ./estechfrontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - frontend

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./estechfrontend/dist:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
    networks:
      - frontend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  postgres_data:
