version: '3.9'

services:
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - backend

  backend:
    build:
      context: ./estechbackend
    container_name: backend
    volumes:
      - ./estechbackend:/app
    env_file:
      - ./estechbackend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - backend

  frontend:
    build:
      context: ./estechfrontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - frontend

  nginx:
    image: nginx:alpine
    volumes:
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./estechfrontend/dist:/usr/share/nginx/html
    - /etc/letsencrypt/live/estechpc.ru/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
    - /etc/letsencrypt/live/estechpc.ru/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
    networks:
      - frontend
      - backend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge

volumes:
  postgres_data:
