version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: estechdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

  backend:
    build: ./estechbackend
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./estechbackend:/app
      - static_volume:/app/static
    environment:
      - DATABASE_URL=postgres://postgres:root@postgres:5432/estechdb
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  frontend:
    build: ./estechfrontend
    ports:
      - "8080:80"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/static
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
  static_volume:
