# Generated by Django 5.0.4 on 2024-09-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_cartitem_updated_at_likeslist_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='likeslist',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
